# Generated by Django 5.0.1 on 2024-03-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the facility', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of the facility', max_length=255, null=True)),
                ('is_reservable', models.BooleanField(default=False, help_text='Is the facility reservable?')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.CharField(help_text='Type of amenities', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of the amenities', max_length=255, null=True)),
                ('facility', models.ForeignKey(help_text='Facility associated with the amenities', on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Amenities',
                'verbose_name_plural': 'Facility Amenities',
                'ordering': ['amenities'],
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Image file for the facility', upload_to='facilities/images/')),
                ('description', models.CharField(blank=True, help_text='Description of the image', max_length=255, null=True)),
                ('facility', models.ForeignKey(help_text='Facility associated with the image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Image',
                'verbose_name_plural': 'Facility Images',
                'ordering': ['facility', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='Description of the review', max_length=255, null=True)),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating of the facility', max_digits=2)),
                ('facility', models.ForeignKey(help_text='Facility associated with the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Review',
                'verbose_name_plural': 'Facility Reviews',
                'ordering': ['-rating'],
            },
        ),
    ]
