# Generated by Django 5.0.1 on 2024-02-24 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the facility', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of the facility', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(help_text='Type of amenities', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of the amenities', max_length=255, null=True)),
                ('facility', models.ForeignKey(help_text='Facility associated with the amenities', on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Amenities',
                'verbose_name_plural': 'Facility Amenities',
                'ordering': ['amenities'],
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file for the facility', upload_to='facilities/images/')),
                ('description', models.CharField(blank=True, help_text='Description of the image', max_length=255, null=True)),
                ('facility', models.ForeignKey(help_text='Facility associated with the image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Image',
                'verbose_name_plural': 'Facility Images',
                'ordering': ['facility', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Description of the review', max_length=255, null=True)),
                ('rating', models.FloatField(help_text='Rating of the facility')),
                ('facility', models.ForeignKey(help_text='Facility associated with the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facility.facility')),
                ('reviewer', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Review',
                'verbose_name_plural': 'Facility Reviews',
                'ordering': ['-rating'],
            },
        ),
    ]
