# Generated by Django 5.0.7 on 2025-02-07 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the facility', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the facility', null=True)),
                ('is_reservable', models.BooleanField(default=False, help_text='Is the facility reservable?')),
                ('base_capacity', models.PositiveIntegerField(blank=True, help_text='Base capacity of the facility', null=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum capacity of the facility', null=True)),
                ('opening_time', models.TimeField(blank=True, help_text='Opening time of the facility', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Closing time of the facility', null=True)),
                ('base_reservation_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Base reservation fee for the facility per hour and base capacity.', max_digits=10, null=True)),
                ('extra_person_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Extra person fee for the facility', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.CharField(help_text='Type of amenities', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of the amenities', max_length=255, null=True)),
                ('facility', models.ForeignKey(help_text='Facility associated with the amenities', on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Amenities',
                'verbose_name_plural': 'Facility Amenities',
                'ordering': ['amenities'],
            },
        ),
        migrations.CreateModel(
            name='FacilityExtraCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.DecimalField(decimal_places=2, help_text='Fee for the facility', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Description of the fee', max_length=255, null=True)),
                ('facility', models.ForeignKey(help_text='Facility associated with the fee', on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Charge',
                'verbose_name_plural': 'Facility Charges',
                'ordering': ['facility', 'charge'],
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Image file for the facility', upload_to='facilities/images/')),
                ('description', models.CharField(blank=True, help_text='Description of the image', max_length=255, null=True)),
                ('facility', models.ForeignKey(help_text='Facility associated with the image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Image',
                'verbose_name_plural': 'Facility Images',
                'ordering': ['facility', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FacilityReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the reservation')),
                ('start_time', models.TimeField(help_text='Time of the reservation')),
                ('end_time', models.TimeField(help_text='End time of the reservation')),
                ('number_of_people', models.PositiveIntegerField(help_text='Number of people for the reservation')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for the reservation', max_digits=10, null=True)),
                ('facility', models.ForeignKey(help_text='Facility associated with the reservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facility.facility')),
                ('user', models.ForeignKey(help_text='User who reserved', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Reservation',
                'verbose_name_plural': 'Facility Reservations',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='Description of the review', max_length=255, null=True)),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating of the facility', max_digits=2)),
                ('facility', models.ForeignKey(help_text='Facility associated with the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facility.facility')),
                ('reviewer', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Review',
                'verbose_name_plural': 'Facility Reviews',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='FacilityReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Image file for the review', upload_to='facilities/reviews/images/')),
                ('description', models.CharField(blank=True, help_text='Description of the image', max_length=255, null=True)),
                ('review', models.ForeignKey(help_text='Review associated with the image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facility.facilityreview')),
            ],
            options={
                'verbose_name': 'Facility Review Image',
                'verbose_name_plural': 'Facility Review Images',
                'ordering': ['review', 'id'],
            },
        ),
    ]
