# Generated by Django 4.2.7 on 2024-01-20 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityreview',
            name='review_text',
        ),
        migrations.AddField(
            model_name='facilityreview',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the review', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the facility', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(help_text='Name of the facility', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilityamenities',
            name='amenities',
            field=models.CharField(help_text='Type of amenities', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilityamenities',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the amenities', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facilityamenities',
            name='facility',
            field=models.ForeignKey(help_text='Facility associated with the amenities', on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='facilityimage',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facilityimage',
            name='facility',
            field=models.ForeignKey(help_text='Facility associated with the image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='facilityimage',
            name='image',
            field=models.ImageField(help_text='Image file for the facility', upload_to='facilities/images/'),
        ),
        migrations.AlterField(
            model_name='facilityreview',
            name='facility',
            field=models.ForeignKey(help_text='Facility associated with the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='facilityreview',
            name='rating',
            field=models.FloatField(help_text='Rating of the facility'),
        ),
        migrations.AlterField(
            model_name='facilityreview',
            name='reviewer',
            field=models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
