# Generated by Django 5.0.1 on 2024-02-27 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_reservable',
            field=models.BooleanField(default=False, help_text='Is the facility reservable?'),
        ),
        migrations.CreateModel(
            name='FacilityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the reservation')),
                ('start_time', models.TimeField(help_text='Start time of the reservation')),
                ('end_time', models.TimeField(help_text='End time of the reservation')),
                ('facility', models.ForeignKey(help_text='Facility associated with the reservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facility.facility')),
                ('user', models.ForeignKey(help_text='User who made the reservation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Reservation',
                'verbose_name_plural': 'Facility Reservations',
                'ordering': ['facility', 'date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='FacilityInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the installment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the installment', max_digits=10)),
                ('user', models.ForeignKey(help_text='User who made the installment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(help_text='Facility associated with the installment', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='facility.facilityreservation')),
            ],
            options={
                'verbose_name': 'Facility Installment',
                'verbose_name_plural': 'Facility Installments',
                'ordering': ['facility', 'date'],
            },
        ),
    ]
