# Generated by Django 5.0.7 on 2025-02-23 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityreservation',
            name='user',
            field=models.ForeignKey(help_text='User who reserved', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityreview',
            name='facility',
            field=models.ForeignKey(help_text='Facility associated with the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facility.facility'),
        ),
        migrations.AddField(
            model_name='facilityreview',
            name='reviewer',
            field=models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityreviewimage',
            name='review',
            field=models.ForeignKey(help_text='Review associated with the image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facility.facilityreview'),
        ),
    ]
