# Generated by Django 5.0.1 on 2024-03-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_facility_base_reservation_fee_facility_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='base_reservation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base reservation fee for the facility per hour and 30', max_digits=10, null=True),
        ),
    ]
