# Generated by Django 5.0.1 on 2024-03-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_alter_facility_base_reservation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='base_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Base capacity of the facility', null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='base_reservation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base reservation fee for the facility per hour and base capacity.', max_digits=10, null=True),
        ),
    ]
