# Generated by Django 5.0.1 on 2024-03-01 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0006_alter_facility_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Image file for the review', upload_to='facilities/reviews/images/')),
                ('description', models.CharField(blank=True, help_text='Description of the image', max_length=255, null=True)),
                ('review', models.ForeignKey(help_text='Review associated with the image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facility.facilityreview')),
            ],
            options={
                'verbose_name': 'Facility Review Image',
                'verbose_name_plural': 'Facility Review Images',
                'ordering': ['review', 'id'],
            },
        ),
    ]
