# Generated by Django 5.0.1 on 2024-03-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0007_facilityreviewimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityextracharge',
            options={'ordering': ['facility', 'charge'], 'verbose_name': 'Facility Charge', 'verbose_name_plural': 'Facility Charges'},
        ),
        migrations.RenameField(
            model_name='facilityextracharge',
            old_name='Charge',
            new_name='charge',
        ),
        migrations.AlterField(
            model_name='facilityextracharge',
            name='facility',
            field=models.ForeignKey(help_text='Facility associated with the fee', on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='facility.facility'),
        ),
    ]
