# Generated by Django 5.0.1 on 2024-03-01 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type or category of the staff', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the role', null=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Role',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(default=None, editable=False, help_text='6-digit unique identifier for the task', max_length=6, unique=True)),
                ('task_description', models.CharField(default='Prepare The Room', help_text='Description of the task', max_length=200)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current status of the task', max_length=20)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, help_text='Job to be performed', max_length=200, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Task Check List',
                'verbose_name_plural': 'Task Check Lists',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(help_text='Name of the inventory item', max_length=200)),
                ('item_quantity', models.IntegerField(help_text='Quantity of the inventory item')),
                ('for_facility', models.ForeignKey(blank=True, help_text='Facility for the inventory item', null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('for_room', models.ForeignKey(blank=True, help_text='Room for the inventory item', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID of the staff')),
                ('staff_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy '), ('assigned', 'Assigned')], default='available', help_text='Current status of the staff', max_length=20)),
                ('role', models.ForeignKey(help_text='Role of the staff', on_delete=django.db.models.deletion.CASCADE, to='management.role')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'Staffs',
                'ordering': ['-created_at'],
            },
        ),
    ]
