# Generated by Django 4.2.7 on 2023-12-30 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID of the stuff')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update')),
            ],
            options={
                'verbose_name': 'Stuff',
                'verbose_name_plural': 'Stuffs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StuffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_type', models.CharField(help_text='Type or category of the stuff', max_length=200)),
            ],
            options={
                'verbose_name': 'Stuff Type',
                'verbose_name_plural': 'Stuff Types',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(default='Prepare The Room', help_text='Description of the task', max_length=200)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current status of the task', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of task creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update')),
                ('stuff', models.ForeignKey(help_text='Assigned stuff for the task', on_delete=django.db.models.deletion.CASCADE, to='management.stuff')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stuff',
            name='stuff_type',
            field=models.ForeignKey(help_text='Type or category of the stuff', on_delete=django.db.models.deletion.CASCADE, to='management.stufftype'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
