# Generated by Django 5.0.1 on 2024-02-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_role_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id'], 'verbose_name': 'Role', 'verbose_name_plural': 'Role'},
        ),
    ]
