# Generated by Django 5.0.7 on 2025-02-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the staff', null=True, upload_to='staffs/'),
        ),
    ]
