# Generated by Django 5.0.1 on 2024-02-14 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_remove_facilityreview_review_text_and_more'),
        ('main', '0003_alter_installment_options_alter_payment_options_and_more'),
        ('management', '0002_alter_staff_created_at_alter_staff_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the inventory item', max_length=200)),
                ('quantity', models.IntegerField(help_text='Quantity of the inventory item')),
                ('for_facility', models.ForeignKey(blank=True, help_text='Facility for the inventory item', null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('for_room', models.ForeignKey(blank=True, help_text='Room for the inventory item', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room')),
                ('for_staff', models.ForeignKey(blank=True, help_text='Staff for the inventory item', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.staff')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
