# Generated by Django 4.2.7 on 2023-12-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_stuff_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='is_available',
        ),
        migrations.AddField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', help_text='Current status of the stuff', max_length=20),
        ),
    ]
