# Generated by Django 4.2.7 on 2023-12-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_stuff_is_available_stuff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(default=None, editable=False, help_text='6-digit unique identifier for the task', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy ')], default='available', help_text='Current status of the stuff', max_length=20),
        ),
    ]
