# Generated by Django 4.2.7 on 2023-12-30 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_installment_options_alter_payment_options_and_more'),
        ('management', '0005_task_task_id_alter_stuff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_room',
            field=models.ForeignKey(default=5, help_text='Assigned room for the task', on_delete=django.db.models.deletion.CASCADE, to='main.room'),
            preserve_default=False,
        ),
    ]
