# Generated by Django 4.2.7 on 2023-12-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_task_assigned_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy '), ('assigned', 'Assigned')], default='available', help_text='Current status of the stuff', max_length=20),
        ),
    ]
