# Generated by Django 4.2.7 on 2023-12-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_stuff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stuff',
            field=models.ForeignKey(blank=True, help_text='Assigned stuff for the task', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.stuff'),
        ),
    ]
