# Generated by Django 4.2.7 on 2023-12-30 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_staff_options_alter_staff_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffType',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='staff_type',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_type',
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(default=1, help_text='Role of the staff', on_delete=django.db.models.deletion.CASCADE, to='management.role'),
            preserve_default=False,
        ),
    ]
