# Generated by Django 4.2.7 on 2023-12-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_rename_stafftype_role_rename_staff_type_role_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Role'},
        ),
    ]
