# Generated by Django 4.2.7 on 2023-12-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_taskqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskqueue',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.task'),
        ),
    ]
