# Generated by Django 4.2.7 on 2023-12-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_remove_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
