version: '3.10'
services:
  web:
    build: .
    command: ./wait-for-it.sh postgres:5432 -- docker-entrypoint.sh
    container_name: zenith_app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - .:/app
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2609
      - POSTGRES_DB=zenith
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
