version: '3'

services:
  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      [
        "sh",
        "-c",
        "source .env && uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload"
      ]

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zenith
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2609
