version: '3'

services:
  django:
    container_name: django
    build: .
    command: bash -c "chmod +x wait-for-it.sh && chmod +x docker-entrypoint.sh && ./wait-for-it.sh postgres:5432 -- ./docker-entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: zenith
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2609
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
