# Generated by Django 4.2.10 on 2024-03-21 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the benefit.', max_length=100)),
                ('description', models.TextField(help_text='A description of the benefit.')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the membership plan.', max_length=100)),
                ('description', models.TextField(help_text='A description of the membership plan.')),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='The monthly price of the membership plan.', max_digits=10)),
                ('price_annually', models.DecimalField(decimal_places=2, help_text='The annual price of the membership plan.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the membership tier.', max_length=100)),
                ('description', models.TextField(help_text='A description of the membership tier.')),
                ('benefits', models.ManyToManyField(help_text='The benefits included in the membership tier.', to='membership.benefit')),
            ],
            options={
                'verbose_name': 'Membership Tier',
                'verbose_name_plural': 'Membership Tiers',
            },
        ),
        migrations.CreateModel(
            name='MembershipTierMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_mappings', to='membership.membershipplan')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_mappings', to='membership.membershiptier')),
            ],
            options={
                'verbose_name': 'Membership Tier Mapping',
                'verbose_name_plural': 'Membership Tier Mappings',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The start date of the membership.')),
                ('end_date', models.DateField(help_text='The end date of the membership.')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='membership.membershipplan')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
            },
        ),
    ]
