# Generated by Django 5.0.7 on 2025-02-23 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='membership.membershipplan'),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='benefits',
            field=models.ManyToManyField(help_text='The benefits included in the membership tier.', to='membership.benefit'),
        ),
        migrations.AddField(
            model_name='membershiptiermapping',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_mappings', to='membership.membershipplan'),
        ),
        migrations.AddField(
            model_name='membershiptiermapping',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_mappings', to='membership.membershiptier'),
        ),
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
