# Generated by Django 4.2.10 on 2024-03-21 06:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the device', max_length=100)),
                ('client_id', models.CharField(help_text='Unique identifier for the device', max_length=100, unique=True)),
                ('qos', models.IntegerField(choices=[(0, 'QoS 0'), (1, 'QoS 1'), (2, 'QoS 2'), (3, 'QoS Auto')], default=0, help_text='Quality of Service for the device')),
                ('status', models.BooleanField(default=False, help_text='Status of the device (active/inactive)')),
                ('description', models.TextField(blank=True, help_text='Description of the device', null=True)),
                ('installation_date', models.DateField(help_text='Date when the device was installed')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the device type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the device type', null=True)),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FacilityDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Location of the device in the facility', max_length=100)),
            ],
            options={
                'verbose_name': 'Facility Device',
                'verbose_name_plural': 'Facility Devices',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Topic: ie. /device/temperature', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of the topic', max_length=255, null=True)),
                ('device', models.ForeignKey(help_text='Device', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='iot.device')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Location of the device in the room', max_length=100)),
                ('device', models.ForeignKey(help_text='Device installed in the room', on_delete=django.db.models.deletion.CASCADE, to='iot.device')),
            ],
            options={
                'verbose_name': 'Room Device',
                'verbose_name_plural': 'Room Devices',
            },
        ),
    ]
