# Generated by Django 4.2.7 on 2024-01-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_initial'),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the device type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the device type', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the device type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the device type was last updated')),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the device', max_length=100)),
                ('device_id', models.CharField(help_text='Unique identifier for the device', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the device', null=True)),
                ('status', models.BooleanField(default=False, help_text='Status of the device (active/inactive)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the device was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the device was last updated')),
                ('device_type', models.ForeignKey(help_text='Type of the device', on_delete=django.db.models.deletion.CASCADE, to='iot.devicetype')),
            ],
            options={
                'verbose_name': 'Room Device',
                'verbose_name_plural': 'Room Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField(help_text='Date when the device was installed in the room')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the device is currently active in the room')),
                ('device', models.ForeignKey(help_text='Device installed in the room', on_delete=django.db.models.deletion.CASCADE, to='iot.device')),
                ('room', models.ForeignKey(help_text='Room in which the device is installed', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='main.room')),
            ],
            options={
                'verbose_name': 'Room Device',
                'verbose_name_plural': 'Room Devices',
                'unique_together': {('room', 'device')},
            },
        ),
        migrations.CreateModel(
            name='FacilityDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField(help_text='Date when the device was installed in the facility')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the device is currently active in the facility')),
                ('device', models.ForeignKey(help_text='Device installed in the facility', on_delete=django.db.models.deletion.CASCADE, to='iot.device')),
                ('facility', models.ForeignKey(help_text='Facility where the device is installed', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Device',
                'verbose_name_plural': 'Facility Devices',
                'unique_together': {('facility', 'device')},
            },
        ),
    ]
