# Generated by Django 4.2.10 on 2024-03-16 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitydevice',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, help_text='Location of the device in the facility', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomdevice',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, help_text='Location of the device in the room', max_length=100),
            preserve_default=False,
        ),
    ]
