# Generated by Django 5.0.7 on 2025-02-14 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdevice',
            name='room',
            field=models.ForeignKey(help_text='Room in which the device is installed', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='main.room'),
        ),
        migrations.AddField(
            model_name='topic',
            name='device',
            field=models.ForeignKey(help_text='Device', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='iot.device'),
        ),
        migrations.AlterUniqueTogether(
            name='facilitydevice',
            unique_together={('facility', 'device')},
        ),
        migrations.AlterUniqueTogether(
            name='roomdevice',
            unique_together={('room', 'device')},
        ),
    ]
