# Generated by Django 5.0.7 on 2024-07-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the device', max_length=255, null=True),
        ),
    ]
