# Generated by Django 4.2.7 on 2024-01-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_alter_device_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['id'], 'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Types'},
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
