# Generated by Django 4.2.10 on 2024-03-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_facilitydevice_location_roomdevice_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='Topic: ie. /device/temperature', max_length=100),
        ),
    ]
