# Generated by Django 4.2.7 on 2024-01-24 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('iot', '0003_alter_devicetype_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomdevice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roomdevice',
            name='device',
        ),
        migrations.RemoveField(
            model_name='roomdevice',
            name='room',
        ),
        migrations.AddField(
            model_name='device',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='device',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='FacilityDevice',
        ),
        migrations.DeleteModel(
            name='RoomDevice',
        ),
    ]
