# Generated by Django 4.2.7 on 2024-01-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_installment_options_alter_payment_options_and_more'),
        ('facility', '0002_remove_facilityreview_review_text_and_more'),
        ('iot', '0004_alter_roomdevice_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='object_id',
        ),
        migrations.AddField(
            model_name='device',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
    ]
