# Generated by Django 4.2.7 on 2024-01-24 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_remove_facilityreview_review_text_and_more'),
        ('main', '0003_alter_installment_options_alter_payment_options_and_more'),
        ('iot', '0005_remove_device_content_type_remove_device_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='device',
            name='room',
        ),
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation_date', models.DateField(help_text='Date when the device was installed')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the device is currently active')),
                ('device', models.ForeignKey(help_text='Device installed in the room', on_delete=django.db.models.deletion.CASCADE, to='iot.device')),
                ('room', models.ForeignKey(help_text='Room in which the device is installed', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='main.room')),
            ],
            options={
                'verbose_name': 'Room Device',
                'verbose_name_plural': 'Room Devices',
                'unique_together': {('room', 'device')},
            },
        ),
        migrations.CreateModel(
            name='FacilityDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation_date', models.DateField(help_text='Date when the device was installed')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the device is currently active')),
                ('device', models.ForeignKey(help_text='Device installed in the facility', on_delete=django.db.models.deletion.CASCADE, to='iot.device')),
                ('facility', models.ForeignKey(help_text='Facility where the device is installed', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility Device',
                'verbose_name_plural': 'Facility Devices',
                'unique_together': {('facility', 'device')},
            },
        ),
    ]
