# Generated by Django 4.2.7 on 2024-01-24 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_device_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitydevice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='facilitydevice',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='facilitydevice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='facilitydevice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='roomdevice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roomdevice',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='roomdevice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='roomdevice',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='device',
            name='installation_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the device was installed'),
            preserve_default=False,
        ),
    ]
