# Generated by Django 4.2.7 on 2024-01-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_remove_facilitydevice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(help_text='Unique identifier for the device', max_length=100, unique=True),
        ),
    ]
