# Generated by Django 4.2.7 on 2024-01-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_title_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
    ]
