# Generated by Django 5.0.1 on 2024-03-01 14:03

import django.core.validators
import main.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, help_text='Floor level, indicating the position of the floor in the building.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the floor, providing additional information.', null=True)),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('nid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('preferences', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='guests')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=main.models.Installment.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('installment_type', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Full', 'Full')], default='First', max_length=20)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_status', models.CharField(default='Pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Banking', 'Mobile Banking')], default='Cash', max_length=20)),
                ('is_refunded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Banking', 'Mobile Banking')], default='Cash', max_length=20)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(default=main.models.Reservation.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reservation_status', models.CharField(choices=[('Reserved', 'Reserved'), ('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-Out'), ('Canceled', 'Canceled')], default='Reserved', max_length=20)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_at'],
                'get_latest_by': 'start_date',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1.'), django.core.validators.MaxValueValidator(10, message='Rating must be at most 10.')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='room/review/')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_label', models.CharField(help_text='A label uniquely identifying the room on its floor.', max_length=1)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of occupants the room can accommodate.')),
                ('description', models.TextField(blank=True, help_text='Additional information or features of the room.', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Indicates whether the room is currently available for booking.')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['floor', 'room_label'],
            },
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the amenity, providing a brief name or description.', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Detailed description of the amenity.', max_length=250, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Indicates whether the amenity is currently available.')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['room', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room/images/')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['room'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(help_text='Type of the room, describing its category or purpose.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per night for this room type.', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Additional details about the room type.', null=True)),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['room_type'],
            },
        ),
    ]
