# Generated by Django 4.2.7 on 2024-01-20 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.installment'),
        ),
        migrations.AddField(
            model_name='installment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reservation'),
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amenity',
            name='room',
            field=models.ForeignKey(help_text='The room to which this amenity is associated.', on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
    ]
