# Generated by Django 4.2.7 on 2024-01-24 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Installments'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Refunds'},
        ),
        migrations.RemoveField(
            model_name='installment',
            name='installment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='refund_date',
        ),
        migrations.AddField(
            model_name='installment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
