# Generated by Django 5.0.7 on 2025-03-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='id',
        ),
        migrations.AlterField(
            model_name='floor',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Floor level, indicating the position of the floor in the building.', primary_key=True, serialize=False, unique=True),
        ),
    ]
