# Generated by Django 5.0.1 on 2024-03-01 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='alt_text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room/review/images/')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.review')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
                'ordering': ['review'],
            },
        ),
    ]
