# Generated by Django 4.2.11 on 2024-04-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id', 'floor', 'room_label'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(help_text='The type or category of the room.', on_delete=django.db.models.deletion.PROTECT, to='main.roomtype'),
        ),
    ]
