# Generated by Django 5.0.7 on 2025-02-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='image',
        ),
    ]
