# Generated by Django 4.2.7 on 2023-12-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_comment_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-Out'), ('Canceled', 'Canceled')], default='Reserved', max_length=20),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
