# Generated by Django 5.0.1 on 2024-02-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_room_images_roomimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenity',
            new_name='RoomAmenity',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.room'),
        ),
    ]
