# Generated by Django 4.2.11 on 2024-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_room_options_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='is_elevator_accessible',
            field=models.BooleanField(default=True, help_text='Indicates whether the floor is accessible by elevator.'),
        ),
    ]
