# Generated by Django 5.0.1 on 2024-02-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_refund_refund_method_alter_roomamenity_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='main.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='main.installment'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='main.payment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.room'),
        ),
        migrations.AlterField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.guest'),
        ),
        migrations.AlterField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(help_text='The floor to which this room belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='main.floor'),
        ),
    ]
