# Generated by Django 4.2.7 on 2023-12-16 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_installment_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['installment_date'], 'verbose_name_plural': 'Installments'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'get_latest_by': 'start_date', 'ordering': ['start_date'], 'verbose_name_plural': 'Reservations'},
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='amount',
            new_name='installment_amount',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='due_date',
        ),
        migrations.AddField(
            model_name='installment',
            name='installment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='installment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='installment_type',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('installment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.installment')),
            ],
            options={
                'verbose_name_plural': 'Payments',
                'ordering': ['payment_date'],
            },
        ),
    ]
