# Generated by Django 5.0.1 on 2024-02-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_installment_reservation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='availability',
            new_name='is_available',
        ),
    ]
