# Generated by Django 5.0.1 on 2024-02-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_availability_room_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomamenity',
            old_name='availability',
            new_name='is_available',
        ),
    ]
