# Generated by Django 5.0.1 on 2024-02-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_availability_roomamenity_is_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('floor', 'room_label')},
        ),
    ]
