# Generated by Django 4.2.7 on 2023-12-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_reservation_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='payment_status',
            new_name='_payment_status',
        ),
    ]
