# Generated by Django 4.2.7 on 2023-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
