# Generated by Django 4.2.7 on 2023-12-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_installment_installment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True, help_text='Description of the floor', null=True)),
            ],
            options={
                'verbose_name_plural': 'Floor',
                'ordering': ['floor'],
            },
        ),
    ]
