# Generated by Django 4.2.7 on 2023-12-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['level'], 'verbose_name_plural': 'Floors'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Room Types'},
        ),
        migrations.RemoveField(
            model_name='floor',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
        migrations.AddField(
            model_name='floor',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Floor level, indicating the position of the floor in the building.', unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(help_text='The floor to which this room belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.floor'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_label',
            field=models.CharField(default=1, help_text='A label uniquely identifying the room on its floor.', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amenity',
            name='availability',
            field=models.BooleanField(default=True, help_text='Indicates whether the amenity is currently available.'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.CharField(blank=True, help_text='Detailed description of the amenity.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='room',
            field=models.ForeignKey(help_text='The room to which this amenity is associated.', on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='title',
            field=models.CharField(help_text='Title of the amenity, providing a brief name or description.', max_length=100),
        ),
        migrations.AlterField(
            model_name='floor',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the floor, providing additional information.', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=True, help_text='Indicates whether the room is currently available for booking.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Maximum number of occupants the room can accommodate.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Additional information or features of the room.', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ImageField(blank=True, help_text="Images showcasing the room's interior or features.", null=True, upload_to='room/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(help_text='The type or category of the room.', on_delete=django.db.models.deletion.CASCADE, to='main.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the room type.', null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per night for this room type.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(help_text='Type of the room, describing its category or purpose.', max_length=100),
        ),
    ]
