# Generated by Django 4.2.7 on 2023-12-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_amenity_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(help_text='The floor to which this room belongs.', on_delete=django.db.models.deletion.CASCADE, to='main.floor'),
        ),
    ]
