# Generated by Django 4.2.7 on 2023-12-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_room_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_id',
        ),
    ]
