# Generated by Django 4.2.7 on 2023-12-18 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='guest',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
