# Generated by Django 4.2.7 on 2023-12-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_guest_name_guest_nid_alter_guest_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='updated_contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_nid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
