# Generated by Django 4.2.7 on 2023-12-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_updated_contact_info_reservation_contact_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
    ]
