# Generated by Django 4.2.7 on 2023-12-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_reservation_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Guest',
            new_name='guest',
        ),
    ]
