# Generated by Django 4.2.7 on 2023-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_guest_options_guest_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='contact_info',
            new_name='contact_number',
        ),
        migrations.AlterField(
            model_name='guest',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
