# Generated by Django 4.2.7 on 2023-12-21 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0033_remove_reservation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={},
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='contact_number',
            new_name='contact_info',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='guest',
            name='nid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False)),
                ('is_stuff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__created_at'],
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.userprofile'),
            preserve_default=False,
        ),
    ]
