# Generated by Django 4.2.7 on 2023-12-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_guest_user_profile_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
