# Generated by Django 4.2.7 on 2023-12-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_is_active_guest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Guests'},
        ),
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['date'], 'verbose_name_plural': 'Installments'},
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='installment_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='installment_date',
            new_name='date',
        ),
    ]
