# Generated by Django 4.2.7 on 2023-12-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_installment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['installment_date'], 'verbose_name_plural': 'Installments'},
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='amount',
            new_name='installment_amount',
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='date',
            new_name='installment_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='status',
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_type',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Full', 'Full')], default='First', max_length=20, unique=True),
        ),
    ]
