# Generated by Django 4.2.7 on 2023-12-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_installment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='installment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
