# Generated by Django 4.2.7 on 2023-12-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_installment_installment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
