# Generated by Django 4.2.7 on 2023-12-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_reservation_created_at_reservation_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_amount',
        ),
    ]
