# Generated by Django 4.2.7 on 2023-12-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_reservation_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='installment_type',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Full', 'Full')], default='First', max_length=20),
        ),
    ]
