# Generated by Django 4.2.7 on 2023-12-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_installment_installment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_date', models.DateField(auto_now_add=True)),
                ('refund_method', models.CharField(max_length=100)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.payment')),
            ],
            options={
                'verbose_name_plural': 'Refunds',
                'ordering': ['refund_date'],
            },
        ),
    ]
