# Generated by Django 4.2.7 on 2023-12-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_payment_is_refunded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['-installment_date'], 'verbose_name_plural': 'Installments'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-refund_date'], 'verbose_name_plural': 'Refunds'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'get_latest_by': 'start_date', 'ordering': ['-created_at'], 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'room_label'], 'verbose_name_plural': 'Rooms'},
        ),
    ]
