# Generated by Django 4.2.7 on 2023-12-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_review_likes_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guests'),
        ),
    ]
