# Generated by Django 4.2.10 on 2024-03-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, help_text="The user's first name.", max_length=255)),
                ('last_name', models.CharField(blank=True, help_text="The user's last name.", max_length=255)),
                ('username', models.CharField(blank=True, help_text="The user's username.", max_length=255, null=True, unique=True)),
                ('email', models.EmailField(help_text="The user's email address.", max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user is active.')),
                ('is_admin', models.BooleanField(default=False, help_text='Whether the user is an admin.')),
                ('is_superuser', models.BooleanField(default=False, help_text='Whether the user is a superuser.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the user was created.')),
                ('last_login', models.DateTimeField(auto_now=True, help_text='The date and time the user last logged in.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
