# Generated by Django 4.2.7 on 2023-12-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_guest_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_stuff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_guest',
        ),
    ]
