# Generated by Django 4.2.7 on 2023-12-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_is_admin_user_is_stuff_remove_user_is_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stuff',
            new_name='is_admin',
        ),
    ]
